language: node_js
node_js: stable

sudo: required
services:
  - docker

env:
  global:
    - DOCKERHUB_USER=purduecsusb
    # DOCKERHUB_PASS= in travis web panel

cache:
- yarn: true
  directories:
    - node_modules

before_script:
  - docker pull purduecsusb/openideas || true

script:
  - docker build --pull --cache-from purduecsusb/openideas --tag purduecsusb/openideas .
  - yarn run build

after_script:
  - docker images

before_deploy:
  - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASS"

deploy:
  provider: script
  script: docker push purduecsusb/openideas
  on:
    branch: master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fc1de173cb0c69d8f8f2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
