{
  "language": "node_js",
  "node_js": "stable",
  "cache": {
    "yarn": true,
    "directories": [
      "node_modules"
    ]
  },
  "script": [
    "yarn run dev"
  ],
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}
